version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-media-webapp-v2-nextjs
    ports:
      - "3000:3000"
    env_file:
      - .env.local
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: social-media-webapp-v2-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
