name: Social Media Webapp v2 CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if mongosh --quiet mongodb://localhost:27017/test --eval "db.runCommand({ping: 1})" ; then
              echo "MongoDB is up!"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 1
          done

      - name: Run Unit Tests
        run: npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/testdb
          ATLAS_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          NODE_ENV: test
          CI: true

      - name: Prepare Environment Files
        run: |
          # Create .env.local with necessary variables
          echo "MONGODB_URI=mongodb://mongodb:27017/mydb" > .env.local
          echo "NEXT_PUBLIC_APP_URL=http://localhost:3000" >> .env.local
          echo "NODE_ENV=production" >> .env.local

          # Create .env for additional configurations if needed
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
          echo "RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}" >> .env

      - name: Create Docker Compose Configuration
        run: |
          cat > docker-compose.yml << EOL
          services:
            nextjs-app:
              build:
                context: .
                dockerfile: Dockerfile
              container_name: social-media-webapp-v2-nextjs
              ports:
                - "3000:3000"
              env_file:
                - .env.local
                - .env
              environment:
                - NODE_ENV=production
              depends_on:
                - mongodb

            mongodb:
              image: mongo:latest
              container_name: social-media-webapp-v2-mongodb
              ports:
                - "27018:27017"  # Change external port to avoid conflict
              volumes:
                - mongodb_data:/data/db

          volumes:
            mongodb_data:
          EOL

      - name: Verify Docker Compose File
        run: |
          echo "Docker Compose Configuration:"
          cat docker-compose.yml

      - name: Build Docker Image
        run: docker build -t social-media-webapp-v2 .

      - name: Docker Compose Build
        run: docker-compose build

      - name: Docker Compose Validate
        run: docker-compose config

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Check Running Containers
        run: docker ps

      - name: Check Container Logs
        run: docker-compose logs
